meta_product_name: "Style in Peace"
meta_title: "Style In Peace | Sustainable Fashion"
meta_description: "Search sustainability ratings for thousands of fashion brands. Learn their impact on people, planet and animals. Discover new ethical clothing labels."
meta_image: "vogue.png" # should exist in `app/assets/images/`
